### ISSUE TITLE
linter does not highlight no where queries

### ISSUE THREAD

**Issue by duronrulez** [whiteclarkegroup/liquibase-linter#101]
This is the changeset i have:
```
<changeSet id="1" author="AB" context="test">
        <comment>AB</comment>
       <sql>
         <![CDATA[ DELETE FROM test; ]]>
</sql>
</changeSet>
```

This is the config:
```
{
    "fail-fast": false,
    "ignore-context-pattern": null,
    "ignore-files-pattern": null,
    "rules": {
        "modify-data-enforce-where": {
            "values": ["*"],
            "errorMessage": "Updates and deletes must have a where condition"
        }
    }
}
```

Unfortunately there are no errors when i run "liquibase validate".
Any ideas what i may be doing wrong?
I have similar issues with a few more of the rules, is it that the tool does not work with raw sql change sets?

**Comment by davidjgoss** [comment]
@duronrulez yeah the linter makes no effort to check the contents of raw SQL changes - this is not something we’d ever get into. I’d encourage you to use liquibase changes wherever possible if you want to make use of the linting.
