### ISSUE TITLE
enableAfter fails silently if target file is never encountered

### ISSUE THREAD

**Issue by davidjgoss** [whiteclarkegroup/liquibase-linter#103]
You can use `enableAfter` to make a rule (or all rules) only enforced after a particular change log file - see https://whiteclarkegroup.github.io/liquibase-linter/docs/retrofitting

But if the file is never encountered, because it doesn't exist, then the rule (or all rules) will never be enabled, and this happens silently.

We should throw when this happens with an appropriate message.

cc @luke-rogers

**Comment by bbrouwer** [comment]
Alternatively, should this be its own rule? If this were a rule that is implicitly included, I could choose to turn it off via config.

**Comment by davidjgoss** [comment]
No I think this is firmly in the camp of developer error, I don't think it would ever be desired or intentional.
