### ISSUE TITLE
Multiple config files

### ISSUE THREAD

**Issue by bbrouwer** [whiteclarkegroup/liquibase-linter#107]
I'm trying to devise a way where we can have some company wide rules to apply to `lqlint.json`. For example, I'd like to be able to provide a very minimal `lqlint.json` file (even missing entirely) and still apply some company-wide default rules. 

In addition to defaults, I'd like to have some overrides, so that if someone tried to disable a rule, for example, the overrides would turn it back on. 

These default and override rules would need to exist somewhere outside of the repository containing the `lqlint.json` file. Ideally, I could see these being loaded via HTTP GET. I'd prefer that so a developer could simply check out a liquibase repo and start linting without having to do anything else.

Could the `ConfigLoader` be changed to accept a list of resources, load each `Config` individually and then merge the results into a single new `Config`?

**Comment by bbrouwer** [comment]
Or, what if the linter used the same facility that Liquibase uses to find plugins: the ServiceLoader. `LintAwareChangeLogParser` could load my own version of `ConfigLoader`, changing `ConfigLoader` to an interface.

Or should I just implement my own Liquibase plugin, extending `LintAwareChangeLogParser` at a higher priority and override `loadConfig`?

**Comment by davidjgoss** [comment]
Thanks for raising @bbrouwer. This is definitely something we'd like to address.

I'm thinking about ESLint and how it [provides an `extends` option](https://eslint.org/docs/user-guide/configuring#extending-configuration-files) so from your "main" config file you can reference another "base" one to extend from. We could support this being either a relative file system path or a `classpath:` resource.

The tricky bit will then be for us to spec how the extend should work - i.e. to what depth we would mixin config, is there anything we wouldn't bring in from the "base" one, etc.

What do you think @luke-rogers ?

**Comment by bbrouwer** [comment]
I have been digging into this all day. I think I'm getting close to a solution that extends `LintAwareChangeLogParser` and overrides `loadConfig`. I load my list of default rules using the `Config.fromInputStream(inputStream)`, but instead of using an `InputStream` from the `ResourceAccessor`, I'm just loading it from the classpath. I call this `defaultConfig`.

Then I use the stock `ConfigLoader` to load the regular `lqlint.json` into `config`. For every rule name in `config`, I have it replace the entire list of rules for the same name in `defaultConfig`. This way I can eliminate default rules if I want to replace them with something else. 

My work is still in progress, so I don't know if it is actually going to turn out. 

But to your point about figuring out how it should work, I agree; it is not clear. Do we look for `RuleConfig` instances with the same pattern in order to override them? For rules that don't use a pattern, do we just wipe out the entire list of rules? The `Config` doesn't know which rules use patterns and which ones don't, so that could be a problem.

**Comment by davidjgoss** [comment]
> Do we look for RuleConfig instances with the same pattern in order to override them? For rules that don't use a pattern, do we just wipe out the entire list of rules? The Config doesn't know which rules use patterns and which ones don't, so that could be a problem.

I think the MVP for this feature would be a shallow merge of rules e.g. if your main config and your base config both have a key then the main one "wins", no merging of the detail. Also I think rules are the only thing to merge, as I think the other config items are very contextual and wouldn't make sense in a shared config.

@bbrouwer would you be interested in doing a PR for this?

**Comment by luke-rogers** [comment]
I agree I think we should be shallow merging the rules.

In #94 we added support for loading the config from the classpath, to make it easier to have a global config that you could share between projects. Currently the `ConfigLoader` will just return on the first config it finds. Seems like it would be better to load all of the configs it finds and shallow merge. We could follow the liquidate style 'priority' pattern where we can add an optional priority value to `lqlint.json` and merge in order of this priority with highest last/null first.

@bbrouwer seems like this would this cover your requirement?

**Comment by davidjgoss** [comment]
(FWIW I tend to prefer explicit over implicit, but don't feel super strongly in this case)

**Comment by bbrouwer** [comment]
I agree with the shallow merging of rules. I disagree with the solution of loading all resources named `lqlint.json`. It sounds like a recipe that invites unexpected results. I too would prefer a more explicit import. 

I would like to have a library with multiple named standards which I could import. This would allow me to `"import": "classpath:standardA.json"` or `"import": "classpath:standardB.json"` depending on what my requirements are.

If I only had the option of loading things named `lqlint.json`, I would have to make multiple libraries: `standardA.jar` and `standardB.jar`. While doable, it will make it impossible to have a single parent `pom.xml` that makes the correct standard available for use inside my very simple `pom.xml`. Instead, I'd have to make my `pom.xml` include something like this:
```
<plugin>
    <groupId>org.liquibase</groupId>
    <artifactId>liquibase-maven-plugin</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.example.liquibase.standards</groupId>
            <artifactId>standardA</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>
</plugin>
```
That's a whole lot more config than if I setup my parent `pom.xml` with defaults from the parent `pom.xml`. Then my `lqlint.json` could be simply:
```
{
  "import": "classpath:standardA.json"
  ...
}
```
I'd argue the `import` in `lqlint.json` would provide better visibility that I'm using `standardA` with this being in the `lqlint.json` file instead of the `pom.xml`.

I will admit, though, that my primary goal is to eliminate the need for the `lqlint.json` file in most cases, configuring the parent `pom.xml` to load a single, standard `lqlint.json` file. I think #94 is sufficient for that specific goal. I just wish there was something I could put in my `pom.xml` to pick `classpath:standardA.json` instead of passing in from the command line `"-Dlqlint.config.path=classpath:standardA.json"`. For that, I suppose the proposed `import` inside my own `lqlint.json` file will suffice.

I am working on getting approval to provide a PR to do this.

**Comment by davidjgoss** [comment]
This also ties in with #65

**Comment by bbrouwer** [comment]
There's not a lot of detail in #65, so I don't know if what I have will cover it. What I have basically working adds an `import` array/string. 
```
{
    "import": [
        "first.json",
        "second.json"
    ],
    "rules": {
        "object-name": {
            "pattern": "^[A-Z0-9]+$",
            "errorMessage": "Object name '%s' name must be uppercase or numeric characters only"
        }
    }
}
```
How this example will be handled is this:
* First, this config is loaded, recording the `object-name` rules.
* Makes a copy of these rules from this main config (call it `combinedRules`)
* Then it iterates over all the import entries (`first.json` and `second.json`), loading each in order (recursively)
* For each rule in the imported entry
  * If the main config already has the same rule defined, it discards the imported rule
  * If the main config doesn't have the same rule defined, add the rule to the `combinedRules`. This will have the effect of combining rules of the same name from `first.json` and `second.json`
* Make a new config object, which is a copy of the main config, but the rules from `combinedConfig`.

And it is not necessary to specify `import` as an array if you have only one import.
```
{ "import": "first.json" }
```

**Comment by davidjgoss** [comment]
Thanks @bbrouwer, that looks like a nice design to me.

Sorry I was a little cryptic with the link to #65 - I'm not trying to add that the scope of this. Once the import mechanism is in, we should be able to build on it so we can bundle a recommended set of rules with the library and use it with a special case value like:

```json
{
  "import": "recommended"
}
```
