### ISSUE TITLE
Add ability to filter out linting violations ignored from enable-after

### ISSUE THREAD

**Issue by bbrouwer** [whiteclarkegroup/liquibase-linter#111]
Even though I use `enable-after`, all that does is mark violations as ignored. As part of #110 I would like to also add the ability to filter out these ignored violations so reviewers don't have to see all that noise. I'm thinking something like `-Dlqlint.report.ignored=false`

**Comment by bbrouwer** [comment]
Actually, since the config setting is named `enable-after`, wouldn't it be better to not even report those as ignored? That would probably be more helpful to me as it would still make it obvious that new rules were being ignored. I could see reviewers not noticing new changes being marked ignored and this would be one more place to see that.

**Comment by bbrouwer** [comment]
After looking at the code further, I propose adding `Report.addSkipped` to handle the cases that are currently calling `Report.addIgnored` because of `enabled-after`. See [RuleRunner.handleViolation](https://github.com/whiteclarkegroup/liquibase-linter/blob/master/src/main/java/com/whiteclarkegroup/liquibaselinter/config/rules/RuleRunner.java#L96)

**Comment by davidjgoss** [comment]
I agree we should have "skipped" for the `enable-after` case and not write anything out in the console reporter for it. I can probably pick this up today/tomorrow.

**Comment by bbrouwer** [comment]
I'm working on the implementation of this right now. I hope to have clearance next week to contribute it officially.

I was going to add a `-Dlqlint.report.skipped` property to control it. I was going to have the default be to not output skipped violations. Are you instead suggesting we should not even report the skipped violations?

**Comment by bbrouwer** [comment]
As I mentioned on #110, it might be valuable to have on option like `-Dlqlint.report.types=ERROR,IGNORED` (the default) where the full list would be `-Dlqlint.report.types=ERROR,IGNORED,SKIPPED,PASSED`

**Comment by davidjgoss** [comment]
To be honest that feels like more granularity than is necessary. I think the individual reporters will be opinionated on which types of result should be reported and how - for example a JSON one would output everything, a console one would omit skipped, and a markdown one would perhaps just aggregate to a single footnote.

**Comment by luke-rogers** [comment]
Added a comment to #110 which covers some of this but in this case I don't think there is a need to really have `-Dlqlint.report.skipped` - we should just not report those in the console by default.

**Comment by bbrouwer** [comment]
I'm getting back into this and I'm reconsidering the whole notion of having `SKIPPED`. We already have `ignore-file-pattern` and `ignore-context-pattern` which cause rules to never be evaluated and thus never reported. These, along with `enable-after` are all defined in the `lqlint.json` and are distinct from `lql-ignore`, which goes in the change log. That distinction was my original thought for `SKIPPED` vs. `IGNORED`.

`SKIPPED` would then report rules as skipped due to `ignore-file-pattern` and `ignore-context-pattern` as well. And then those properties should be renamed to `skip-file-pattern` and `skip-context-pattern`. But I suggest we don't do any of that.

Instead, I'm going to treat `enable-after` exactly the same way as `ignore-file-pattern` and `ignore-context-pattern` in that these rules will never be evaluated and never reported. `SKIPPED` just won't be a thing to report.

**Comment by bbrouwer** [comment]
Currently, if a change set comment ends with `lql-ignore`, it is never evaluated and thus rule violations are never reported as `IGNORED`. With my proposed change, because that is defined in the liquibase change log, these will now start to be reported as `IGNORED`.
