### ISSUE TITLE
Publish to Central

### ISSUE THREAD

**Issue by davidjgoss** [whiteclarkegroup/liquibase-linter#12]
Per https://central.sonatype.org/pages/ossrh-guide.html

**Comment by davidjgoss** [comment]
https://issues.sonatype.org/browse/OSSRH-42466

**Comment by luke-rogers** [comment]
Version 0.1.0 available in [central](https://search.maven.org/artifact/com.whiteclarkegroup/liquibase-linter/0.1.0/jar)
