### ISSUE TITLE
Support expressing `illegal-change-types` as the xml tag names

### ISSUE THREAD

**Issue by davidjgoss** [whiteclarkegroup/liquibase-linter#13]
e.g. currently to disallow data being loaded from files, I have to do:

```json
"illegal-change-types": [
      "liquibase.change.core.LoadDataChange"
  ]
```

but it'd be good to not make our users go off and find the classname in Liquibase, but rather be able to just use the tag name (which they'll know):

```json
"illegal-change-types": [
      "loadData"
  ]
```

**Comment by luke-rogers** [comment]
#18
