### ISSUE TITLE
Not working from CLI

### ISSUE THREAD

**Issue by aairey** [whiteclarkegroup/liquibase-linter#165]
The [docs](https://whiteclarkegroup.github.io/liquibase-linter/docs/install#command-line) describe a way to run this from the command line.
However we are facing this issue when running the jar:

```bash
➜ java -jar liquibase-linter.jar 
no main manifest attribute, in liquibase-linter.jar
```

Can you please provide a Main manifest so it can be run from CLI as intended?

**Comment by luke-rogers** [comment]
liquibase-linter is not designed to be runnable on its own, it works by being on the classpath of Liquibase. It's added as a `lib` under Liquibase and uses the [extensions feature](https://liquibase.jira.com/wiki/spaces/CONTRIB/overview).

**Comment by aairey** [comment]
Should the documentation be updated then so that is more clear?

**Comment by luke-rogers** [comment]
Agree, the documentation should be improved to make that more clear.
