### ISSUE TITLE
Add one class to implement a rule

### ISSUE THREAD

**Issue by davidjgoss** [whiteclarkegroup/liquibase-linter#27]
Currently the core rules are somewhat hardcoded and to add a new rule you need to write the actual logic and then reference it in several places.

We should restructure the code so a rule is implemented by a single class (with a framework of helpers obviously) that defines how the rule works, the name and what it applies to, which is then automatically picked up by a classpath scanning strategy.

This will ease maintenance of core rules but also allow us to support custom rules.

**Comment by luke-rogers** [comment]
Created a branch to cover this continued migration process [rules-migration](https://github.com/whiteclarkegroup/liquibase-linter/tree/rules-migration)

**Comment by davidjgoss** [comment]
We've done this now.
