### ISSUE TITLE
Possibility to use pattern in ModifyDataEnforceWhereImpl rule

### ISSUE THREAD

**Issue by horvathati** [whiteclarkegroup/liquibase-linter#48]
Currently ModifyDataEnforceWhereImpl rule only works for tables that are defined one-by-one in values argument. It would be nice if pattern could be used for table names.

**Comment by davidjgoss** [comment]
Just an update here, there were some changes to [this rule](https://whiteclarkegroup.github.io/liquibase-linter/docs/rules/modify-data-enforce-where) so the `pattern` config prop is now (optionally) used to ensure the content of the where condition conforms to a pattern.

I don't think this necessarily rules out your request - we could look at a potentially lighter-weight mechanism where you could use placement of an `*` to effectively denote "starts with" or "ends with" for strings in the `values` list.

**Comment by luke-rogers** [comment]
fixed in #98
