### ISSUE TITLE
prevent wrong value type being used

### ISSUE THREAD

**Issue by davidjgoss** [whiteclarkegroup/liquibase-linter#52]
Example:

```xml
<column name="MESSAGE" valueNumeric="Hello World"/>
```

Nothing in the schema stops you from doing this, but Liqubase will just output it without the quotes and it won't run. We could add a rule that errors when the value in `valueNumeric` is not parseable as a long or double.

Could also look at similar issues for other value types

cc @luke-rogers

**Comment by hrabo** [comment]
@davidjgoss @luke-rogers What do you think about having JSON/YAML schema validation rule to prevent typos eg: perConditions. As I know there is schema for xml but not for JSON/YAML. What would be a possible solution to validate JSON/YAML schema?

**Comment by davidjgoss** [comment]
@hrabo interesting point - I would say that would be on Liquibase itself to provide a [JSON schema](https://json-schema.org/) and validate against it at deserialisation time. If there's a gap then the main Liquibase repo is probably the right place to make the change.

(Because liquibase-linter hooks into the plugin lifecycle at a point _after_ the changelog(s) have already been parsed and converted to Java objects, it's kind of too late for us to do anything without a big rearchitecting of how the tool works.)

As for YAML I've never actually seen anything like a schema for that - would be cool if there is one, I think it might get more traction for this kind of thing.

**Comment by davidjgoss** [comment]
Closing as this is not practical to implement - Liquibase does some internal processing and parsing on `setValueNumeric`, so we aren't able to see the value in time.
