### ISSUE TITLE
prevent usage of reserved words

### ISSUE THREAD

**Issue by davidjgoss** [whiteclarkegroup/liquibase-linter#53]

**Comment by davidjgoss** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017

**Comment by davidjgoss** [comment]
https://docs.oracle.com/cd/B10501_01/appdev.920/a42525/apb.htm

**Comment by luke-rogers** [comment]
Feel like this one need a bit more investigation and maybe some test cases if possible.
In `JdbcConnection::attatch` a list of sql keywords is pulled from the metadata and put on the database object. This is then consumed later in `AbstractJdbcDatabase::mustQuoteObjectName`.

Is this issue only occurring only in offline mode where we do not have the jdbc connection to pull the keywords, hence they are not quoted?

**Comment by davidjgoss** [comment]
You're right, that's it - as you say when running against a real database, Liquibase will ask it for a reserved words list and use that to automatically quote the names, but in [offline mode](https://www.liquibase.org/documentation/offline.html) it just skips this, because what else can it do, and that's where we hit the issue internally.

In principal I would still like to have a rule to prevent using reserved words, for this reason, but it's not really practical to have us maintain the lists for each version of each DBMS - presumably Liquibase itself came to the same conclusion, and it's therefore just a gotcha of offline mode.

¯\_(ツ)_/¯
