### ISSUE TITLE
Allow linting subset of files

### ISSUE THREAD

**Issue by elijah-trexler** [whiteclarkegroup/liquibase-linter#67]
Hey all- 

Thanks for the wonderful tool. We have started to integrate into our CI pipeline!

Was wondering if any thought had been given to enabling liquibase-linter for a subset of changelogs. Been working on a project with many historical changelogs we don't want linted and currently we have a very hacky workaround to ensure that liquibase-linter only lints the subset of changes files. Would love if this was natively supported in liquibase-linter somehow, preferable in a way that could easily be integrated into a CI pipeline.

Since each changelog is generally just applied once and then remains in the database, linting historical changelogs serves little purpose, in my eyes.

Thanks,
Elijah

**Comment by davidjgoss** [comment]
@elijah-trexler thanks for the feedback, good to know it's proving useful.

So we currently have a way to ignore changes [based on a pattern match on the context](https://whiteclarkegroup.github.io/liquibase-linter/docs/configure#ignore-context-pattern) - is this what you are hacking with or is there something else you're doing?

I guess the obvious thing would be `ignore-files-pattern` which would do a similar job but pattern matching on the `logicalFilePath` - @luke-rogers do you see any issues?

**Comment by davidjgoss** [comment]
Also there are probably a coupe of things worth mentioning on the point about historical changelogs that are never likely to be run again - if that is truly the case, you could consider:

- Archiving them off to another directory and removing the includes from the main changelog. This would stop the linter going over them, and also stop Liquibase from processing them every time you run it, which is what's happening now
- Re-baselining using [`generateChangeLog`](https://www.liquibase.org/documentation/generating_changelogs.html) so you consolidate all those historical scripts into a single baseline, then give it a context you can pick up with `ignore-context-pattern`

**Comment by luke-rogers** [comment]
@davidjgoss `ignore-files-pattern` would be a good addition that could provide a solution to this issue. We can go ahead and get that added.

As you mention in your alternative options, archiving them off and re-baselining may be the better option as `ignore-files-pattern` wont be effective if your scripts are all in the same directory or don't have some sort of naming pattern that would make historic scripts east to target with this rule.

@elijah-trexler if you want to do something today without re-baselining then you'll have to use `ignore-context-pattern` and change the context of your historic scripts.

**Comment by elijah-trexler** [comment]
@davidjgoss @luke-rogers thank you all for the quick response!

Our current hack is actually detecting changed files using `git diff` and then passing those files into a script which adds `lql-ignore` to all changesets that are not a part of the results of `git diff` (so if I only touch changelog-0003.json, every file but changelog-0003.json has a comment patched in). This is temporary because we have throwaway environments we run the linter in.

We've looked at rolling up changelogs as well as using `ignore-context-pattern`, but it fails our need in one key area- when new rules are introduced it means that all of the changelogs have to be rolled up again (as some recent, unrolled changelog may break that new rule), or the files edited to adjust the context again. I think `ignore-files-pattern`, while useful, would also run into similar issues. While things like rolling up changelogs are important for healthy/managable code, we don't want it to be so tightly coupled to introducing a new rule.

It may just be us using an unusual workflow, but I still feel that the real important use of this tool is linting new changelogs, not the historical ones. If a changelog has already been applied, even if there are linting issues it is difficult/undesirable to fix them. I actually think some sort of `only-lint` option, where changelog paths are passed in, would greatly enhance workflows like ours. Another solution might be to only lint changelogs that would actually be applied by liquibase (thus ignoring historical changelogs).

I hope I've conveyed why our current workflow doesn't quite mesh up with the tools/options available, and why being able to select files for linting may be of use. I hope this doesn't come across as adversarial, we have it up and running and it's been great at saving time on manual reviews- having a more 'in-tool' workflow would just make the team much more accepting of it's use. Thanks again guys!

**Comment by luke-rogers** [comment]
@elijah-trexler 
You do raise an interesting issue about introducing new rules on existing liquibase projects. Within our current workflow we are re-baselining reasonably frequently so this hasn't come up so far. 

However you are correct that it will be problematic to add a new rule into an existing project that has scripts that have run (meaning we shouldn't really change them) but then fail the new rule. 

One way I could image this working is adding a new `enable-from` config property to a rule that will reference a changelog (basically a point in time) to enable the change from. This would mean that the rule will only run against changes after and including the change referenced in the `enable-from` value.

From what you have said above it sounds like something like this would work for you. What do you think?

**Comment by elijah-trexler** [comment]
Hey guys, sorry for the delay! 

`enable-from` would be a real help for us. I still think the "holy grail" would be linting of some arbitrary subset of files although due to how this tool hooks into liquibase-linter that may just end up being out of scope. `enable-from` would solve 99% of our issues and I think be a great addition to the project.

Thanks for working with me on this- I look forward to the release!
