### ISSUE TITLE
How to run linter from command line by passing changelog.xml?

### ISSUE THREAD

**Issue by sudarshanaks** [whiteclarkegroup/liquibase-linter#78]
I don't have any existing java application to include the dependency but I need to run linting on the xml file which used to change database objects. Can anyone help me how I can do that.

**Comment by luke-rogers** [comment]
We need to improve our documentation for the other methods of running liquibase with the linter, such as through the command line.

Starting with the [latest Liquibase release](https://github.com/liquibase/liquibase/releases/download/liquibase-parent-3.8.0/liquibase-3.8.0-bin.zip), I am able to get this to work by adding the [latest Liquibase Linter release jar](https://repo1.maven.org/maven2/com/whiteclarkegroup/liquibase-linter/0.4.0/liquibase-linter-0.4.0.jar) to the `lib` directory, along with the dependencies required by the linter which you can find [here](https://mvnrepository.com/artifact/com.whiteclarkegroup/liquibase-linter/0.4.0). Next add your `lqlint.json` configuration file to the `lib` directory. 

This should be all that is required to get the linting working when running from the command line.

**Comment by duronrulez** [comment]
i know this is closed, but what do you actually need to run on liquibase side to get the linting working? Or is it executing on "update"?
