### ISSUE TITLE
How to restrict execution of DML in liquibase linter ?

### ISSUE THREAD

**Issue by sudarshanaks** [whiteclarkegroup/liquibase-linter#91]
Hi Team,
I maintaining two liquibase liter profile 
1) Execute only DDL and block /reject all DML changes 
2) Execute only DML and block /reject all DDL changes 
I have two different devops pipeline for these two profile, Could you please help me if this can be handled in liquibase linter?

**Comment by sudarshanaks** [comment]
FYI, I'm using liquibase command line

**Comment by sudarshanaks** [comment]
Can I use like below? 

"illegal-change-types": {
                "values": ["sql", "sqlFile","loadData","insert","update","delete"]

**Comment by davidjgoss** [comment]
> Can I use like below?
> 
> "illegal-change-types": {
> "values": ["sql", "sqlFile","loadData","insert","update","delete"]

Yes this would prevent DML changes, best I can tell.

In terms of having seperate configs for your DDL vs DML pipelines, one thing we could look at doing is being able to parameterise the liquibase-linter [config file](https://whiteclarkegroup.github.io/liquibase-linter/docs/configure) location, which you could then manage from your CI tool.

This would still mean having the two config files in your repo - I know you mentioned in #83 that you would be concerned about developers changing that config and being able to circumvent the rules; I think fundamentally you need to look at [ways to instrument control](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) over who can change what in your repository - but we are also looking at the possibility of being able to pull in the liquibase-linter config as an external artifact (i.e. a jar), which might also help.

**Comment by davidjgoss** [comment]
Closing as this should now be achievable by setting `-Dlqlint.config.path` in your CI pipeline, per https://liquibase-linter.dev/docs/configure#custom-lint-config-file-path.
